version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm ci  # or 'npm install' if not using lock file
  build:
    commands:
      - npm run build

artifacts:
  base-directory: dist
  files:
    - '**/*'
